### ISSUE TITLE
np.str depracated issue

### ISSUE THREAD

**Issue by Xiaoyi-ZHANG23** [arung-northwestern/pacmof#2]
Hi, just writing to inform that at line 689 of pacmof.py np.str has deprecated to str and the code will result in attribute error

**Comment by parkjunkil** [comment]
I encountered the same error! Did you resolve this issue?

**Comment by parkjunkil** [comment]
I encountered the same error, and now it is resolved after replacing 'np.str' into 'str'. Hope this helped!

**Comment by arung-northwestern** [comment]
done. thanks!
